version: "3"
services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: onur
      POSTGRES_PASSWORD: 1234
      PGDATA: /data/postgres
      POSTGRES_DB: PostgresDB
    ports:
      - "5433:5432"
   
    restart: unless-stopped